common: &common
  adapter: postgresql
  username: adam
  password: adam

development:
  <<: *common
  database: gamespool_development

test: &test
  <<: *common
  database: gamespool_test

production:
  <<: *common
  database: gamespool

cucumber:
  <<: *test